In [10]:
import numpy as np


j_model = np.array([[1, 0],
                    [0, 1]])
factor = 1.e6
u = np.array([2.e-4, 1.e-4])
delta_x = j_model @ u

a = np.array([1, 0, 0, 0])

for itr in range(1000):
    W = np.array([[u[0], u[1], 0, 0],
                  [0, 0, u[0], u[1]]])
    e = W @ a - delta_x
    a_update = a - factor*W.transpose()@e
    a = a_update
    print(a)

[1.   0.   0.02 0.01]
[1.     0.     0.039  0.0195]
[1.       0.       0.05705  0.028525]
[1.         0.         0.0741975  0.03709875]
[1.         0.         0.09048763 0.04524381]
[1.         0.         0.10596324 0.05298162]
[1.         0.         0.12066508 0.06033254]
[1.         0.         0.13463183 0.06731591]
[1.         0.         0.14790024 0.07395012]
[1.         0.         0.16050522 0.08025261]
[1.         0.         0.17247996 0.08623998]
[1.         0.         0.18385596 0.09192798]
[1.         0.         0.19466317 0.09733158]
[1.         0.         0.20493001 0.102465  ]
[1.         0.         0.21468351 0.10734175]
[1.         0.         0.22394933 0.11197467]
[1.         0.         0.23275187 0.11637593]
[1.         0.         0.24111427 0.12055714]
[1.         0.         0.24905856 0.12452928]
[1.         0.         0.25660563 0.12830282]
[1.         0.         0.26377535 0.13188767]
[1.         0.         0.27058658 0.13529329]
[1.         0.         0.27705725 0.

In [52]:
import numpy as np

factor = 1.e0
learning_rate = 1.e0
j_model = np.array([[1, 0],
                    [0, 0.8]])

deseired_x = np.array([1, 2])
x = np.array([0., 0.])
u = np.array([0., 0.])
a = np.array([0.2, 0, -0.1, 0.1])


for itr in range(100):
    j_model = j_model + np.random.rand(2,2)*0.05
    delta_x = j_model @ u
    x = x + delta_x
    e_pos = deseired_x - x

    W = np.array([[u[0], u[1], 0, 0],
                  [0, 0, u[0], u[1]]])
    e = W @ a - delta_x
    a_update = a - factor*W.transpose()@e
    a = a_update
    j_est = np.reshape(a, (2, 2))

    dx = -2*(deseired_x-x)
    du = dx @ j_est
    delta_u_length = np.linalg.norm(learning_rate*du)
    if delta_u_length < 0.1:
        u = -learning_rate*du
    else:
        u = -learning_rate*du*(0.1/delta_u_length)
    print('position error:', e_pos)
    print('j error:', e)
    print('action:', u)
    print('estimated j:', a)
    print('u length:', delta_u_length)

position error: [1. 2.]
j error: [0. 0.]
action: [-0.   0.1]
estimated j: [ 0.2  0.  -0.1  0.1]
u length: 0.4
position error: [0.99337896 1.91655889]
j error: [-0.00662104 -0.07344111]
action: [0.00339933 0.09994221]
estimated j: [ 0.2         0.0006621  -0.1         0.10734411]
u length: 0.41301676021901507
position error: [0.97861867 1.83116259]
j error: [-0.01401425 -0.07500802]
action: [0.00616833 0.09980958]
estimated j: [ 0.20004764  0.00206272 -0.09974502  0.11484058]
u length: 0.4254308916383744
position error: [0.95997787 1.74400659]
j error: [-0.01720096 -0.07630908]
action: [0.00871834 0.09961923]
estimated j: [ 0.20015374  0.00377954 -0.09927432  0.12245696]
u length: 0.43604837280012104
position error: [0.93446174 1.65428399]
j error: [-0.0233946  -0.07838903]
action: [0.0108437  0.09941033]
estimated j: [ 0.2003577   0.00611009 -0.0985909   0.13026601]
u length: 0.44503748637853663
position error: [0.90495983 1.56005017]
j error: [-0.02672189 -0.08235312]
action: [0.01291